"""Tests of the XAI techniques."""
from __future__ import annotations

import re

import numpy as np
import pandas as pd
import pytest

from src.explainability import surrogate as surrogate_lib
from src.explainability.counterfactuals import (
    CHANGED_COLUMN,
    ActionableFeature,
    CounterfactualSearch,
    default_actionable_features,
    robust_scales,
)
from src.explainability.denial_report import build_denial_letter
from src.explainability.dependence import (
    accumulated_local_effects,
    partial_dependence_curve,
)
from src.explainability.shap_analysis import select_local_cases
from src.utils import config


@pytest.fixture
def rule_data() -> tuple[pd.DataFrame, np.ndarray]:
    """Decisions generated by a known two-variable rule."""
    rng = np.random.default_rng(0)
    frame = pd.DataFrame({"x": rng.uniform(0, 1, 2000),
                          "z": rng.uniform(0, 1, 2000)})
    frame.loc[:99, "z"] = np.nan
    decisions = ((frame["x"] > 0.6) | (frame["z"] > 0.8)).astype(int)
    return frame, decisions.to_numpy()


def test_surrogate_recovers_known_rule(rule_data) -> None:
    frame, decisions = rule_data
    result = surrogate_lib.fit_surrogate(frame, decisions, 0, max_depth=3)
    assert result.fidelity > 0.97
    assert result.fidelity > result.majority_baseline
    rules = surrogate_lib.extract_rules(result, frame, decisions,
                                        config.ACTION_NAMES)
    assert sum(r.n_samples for r in rules) == len(frame)
    assert sum(r.coverage for r in rules) == pytest.approx(1.0)
    text = surrogate_lib.format_rules(rules)
    assert "Rule 1: IF" in text
    assert surrogate_lib.features_used(result, ["x", "z"])[0] in ("x", "z")


def test_surrogate_needs_a_size_limit(rule_data) -> None:
    frame, decisions = rule_data
    with pytest.raises(ValueError):
        surrogate_lib.fit_surrogate(frame, decisions, 0)


def test_rules_merge_repeated_splits() -> None:
    path = (surrogate_lib._Split("x", True, 1.5, False),
            surrogate_lib._Split("x", True, 0.5, False),
            surrogate_lib._Split("y", False, 2.0, True),
            surrogate_lib._Split("y", True, 5.0, True))
    assert surrogate_lib._simplify(path) == (
        "x <= 0.5", "2 < y <= 5 (or missing)")


def test_fidelity_curve_increases(rule_data) -> None:
    frame, decisions = rule_data
    curve = surrogate_lib.fidelity_curve(frame, decisions, (2, 4, 8), 0)
    assert curve["fidelity"].is_monotonic_increasing


def _toy_score(frame: pd.DataFrame) -> np.ndarray:
    """Default probability driven by utilisation and debt amount."""
    debt = frame[config.DEBT_RATIO] * frame[config.MONTHLY_INCOME]
    logit = -3 + 4 * frame[config.REVOLVING_UTILIZATION] + debt / 2000
    return (1 / (1 + np.exp(-logit))).to_numpy()


@pytest.fixture
def toy_client() -> pd.Series:
    """A client denied by the toy score at threshold 0.3."""
    return pd.Series({
        config.REVOLVING_UTILIZATION: 0.9,
        config.DEBT_RATIO: 0.4,
        config.MONTHLY_INCOME: 3000.0,
        config.OPEN_CREDIT_LINES: 6.0,
    })


def test_counterfactual_is_valid_and_plausible(toy_client) -> None:
    scales = pd.Series(1.0, index=list(config.ACTIONABLE_DIRECTIONS))
    search = CounterfactualSearch(_toy_score, default_actionable_features(),
                                  scales, 0.3, 2000, seed=0)
    result = search.generate(toy_client, 2)
    assert result.found and result.original_proba >= 0.3
    best = result.table.iloc[1]
    assert best["default_proba"] < 0.3
    assert best[config.REVOLVING_UTILIZATION] <= 0.9
    assert best[config.MONTHLY_INCOME] <= 3000 * (
        1 + config.MAX_INCOME_INCREASE)
    assert best[config.OPEN_CREDIT_LINES] == int(
        best[config.OPEN_CREDIT_LINES])
    assert best[CHANGED_COLUMN]


def test_counterfactual_keeps_debt_amount_when_income_rises() -> None:
    feature = ActionableFeature(config.MONTHLY_INCOME, "increase", 0.5)
    client = pd.Series({config.MONTHLY_INCOME: 1000.0,
                        config.DEBT_RATIO: 0.6})
    records = pd.DataFrame({config.MONTHLY_INCOME: [1500.0],
                            config.DEBT_RATIO: [0.6]})
    out = CounterfactualSearch._keep_debt_consistent(records, client)
    assert out[config.DEBT_RATIO].iloc[0] == pytest.approx(0.4)
    assert feature.bounds(1000.0) == (1000.0, 1500.0)
    assert feature.bounds(np.nan) is None


def test_counterfactual_reports_impossible_cases(toy_client) -> None:
    scales = pd.Series(1.0, index=list(config.ACTIONABLE_DIRECTIONS))
    search = CounterfactualSearch(lambda f: np.ones(len(f)),
                                  default_actionable_features(), scales,
                                  0.3, 100, seed=0)
    result = search.generate(toy_client, 2)
    assert not result.found and len(result.table) == 1


def test_robust_scales_are_positive() -> None:
    frame = pd.DataFrame({"a": [1.0, 1.0, 1.0, 5.0], "b": [0.0] * 4})
    scales = robust_scales(frame, ["a", "b"])
    assert (scales > 0).all()


def test_denial_letter_withholds_age() -> None:
    client = pd.Series({config.AGE: 23.0, config.REVOLVING_UTILIZATION: 0.95,
                        config.PAST_DUE_90: 2.0})
    drivers = pd.Series({config.AGE: 0.5, config.REVOLVING_UTILIZATION: 0.3,
                         config.PAST_DUE_90: 0.2})
    counterfactual = pd.Series({config.REVOLVING_UTILIZATION: 0.4,
                                CHANGED_COLUMN:
                                    config.REVOLVING_UTILIZATION})
    letter, withheld = build_denial_letter(client, drivers, counterfactual)
    assert withheld == [config.AGE]
    assert not re.search(r"\bage\b", letter.lower())
    assert "95%" in letter and "40%" in letter


def test_denial_letter_skips_zero_counts() -> None:
    client = pd.Series({config.PAST_DUE_30_59: 0.0, config.PAST_DUE_90: 1.0})
    drivers = pd.Series({config.PAST_DUE_30_59: 0.4,
                         config.PAST_DUE_90: 0.3})
    letter, _ = build_denial_letter(client, drivers)
    assert "30-59" not in letter and "90 days" in letter


def test_pdp_and_ale_of_linear_function() -> None:
    rng = np.random.default_rng(0)
    matrix = pd.DataFrame({"a": rng.uniform(0, 1, 500),
                           "b": rng.uniform(0, 1, 500)})

    def proba_fn(frame: pd.DataFrame) -> np.ndarray:
        return (0.2 * frame["a"] + 0.1 * frame["b"]).to_numpy()

    pdp = partial_dependence_curve(proba_fn, matrix, "a", 10)
    ale = accumulated_local_effects(proba_fn, matrix, "a", 10)
    assert np.all(np.diff(pdp.values) > 0)
    assert np.all(np.diff(ale.values) > 0)
    assert ale.values[-1] - ale.values[0] == pytest.approx(
        0.2 * (ale.index[-1] - ale.index[0]), rel=0.15)


def test_select_local_cases() -> None:
    proba = np.array([0.01, 0.12, 0.5, 0.09, 0.2])
    cases = select_local_cases(proba, 0.1)
    assert cases == {"clear_denial": 2, "borderline_denial": 1,
                     "clear_approval": 0}
